### PR TITLE
Made Header Responsive

### PR DESCRIPTION
**Pull request by shawavisek35**
- Header made responsive for small screen. Check out this screenshot for more reference.
- Minor bug fixes.
head1
Screenshot_20201108_111725
Screenshot_20201108_111821

### CODE REVIEW

**Review by abhinavsri360 — APPROVED** [review]
LGTM

**Comment by abhinavsri360** [comment]
@shawavisek35 are you using different branches to make PR's?

**Comment by shawavisek35** [comment]
> @shawavisek35 are you using different branches to make PR's?

No I am making PR from my branch only, i.e. shawavisek35_branch

**Comment by abhinavsri360** [comment]
It's better to fork -> branch -> PR in my opinion. Let's follow the same for future cases, this will avoid unusual conflicts as rebasing is important.

**Comment by bestinbthomas** [comment]
> > @shawavisek35 are you using different branches to make PR's?
> 
> No I am making PR from my branch only, i.e. shawavisek35_branch

if so, then make different branches for each new feature, don't use same branch

**Review by bestinbthomas — APPROVED** [review]

**Pull request merged**
